package com.jdw.clc;

import org.junit.Test;

import static org.junit.Assert.*;       // generated by IntelliJ

/**
 * Created by jdwilson on 8/21/15.
 */
public class EmployeeFactoryTest {

    @Test
    public void testCreateManagerEmployee() throws EmployeeFactoryException {
        Employee manager = EmployeeFactory.createEmployee(Employee.EmployeeRole.MANAGER);
        assertNotNull(manager);
        assertTrue(manager instanceof Manager);     // verifies ManagerFunctions should be available
        assertEquals(Employee.EmployeeRole.MANAGER, manager.getRole());
        assertEquals(300.00, manager.getExpenseAllocation(), 0.005);    // note, this may change to int to simpify.
        // todo add tests for ManagerFunctions
    }

    @Test
    public void testCreateDeveloperEmployee() throws EmployeeFactoryException {
        Employee developer = EmployeeFactory.createEmployee(Employee.EmployeeRole.DEVELOPER);
        assertNotNull(developer);
        assertEquals(Employee.EmployeeRole.DEVELOPER, developer.getRole());
        assertEquals(1000.00, developer.getExpenseAllocation(), 0.005);    // note, this may change to int to simpify
    }

    @Test
    public void testCreateQATesterEmployee() throws EmployeeFactoryException  {
        Employee qa_tester = EmployeeFactory.createEmployee(Employee.EmployeeRole.QA_TESTER);
        assertNotNull(qa_tester);
        assertEquals(Employee.EmployeeRole.QA_TESTER, qa_tester.getRole());
        assertEquals(500.00, qa_tester.getExpenseAllocation(), 0.005);    // note, this may change to int to simpify
    }

    @Test(expected=EmployeeFactoryException.class)
    public void testCreateInvalidEmployee() throws EmployeeFactoryException {
        Employee invalidEmployee = EmployeeFactory.createEmployee(Employee.EmployeeRole.UNASSIGNED);
    }
}